clear
	echo -E '.'
	echo -E '├── prebeshell.sh'
	echo -E '├── ayuda'
	echo -E '│   ├── milpaa.sh'
	echo -E '│   ├── aiudaa.sh'
	echo -E '│   ├── wachara.sh'
	echo -E '│   ├── creditosa.sh'
	echo -E '│   ├── infosisa.sh'
	echo -E '└── milpita'
	echo -E '│   ├── milpac.sh'
        echo -E '│   ├── milpat.sh'
        echo -E '│   └── milpas.sh'
	echo -E '└── cositas'
	echo -E '    ├── milpa.sh'
	echo -E '    ├── aiuda.sh'
	echo -E '    ├── wachar.sh'
	echo -E '    ├── creditos.sh'
	echo -E '    ├── infosis.sh'
	echo -E '    ├── games'
	echo -E '    │   ├── ahorcado.sh'
	echo -E '    │   └── gato.sh'
	echo -E '    └── prebesonidero.sh'

